### OK 개인 권한으로 회원가입을 합니다.
POST http://localhost:80/enroll/personal
Content-Type: application/json

{
  "username": "admin3",
  "name": "한장현",
  "phoneNumber": "010-0000-0000",
  "password": "test"
}

### OK 회원정보를 수정 합니다.
PUT http://localhost:80/api/account/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

{
  "name": "김종완",
  "phoneNumber": "010-1111-1111"
}

### OK 회원정보를 가져옵니다..
GET http://localhost:80/api/account/me
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

### OK 회사 회원정보를 가져옵니다..
GET http://localhost:80/api/account/me/company
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU


### OK 회원정보를 수정 합니다. 개인 사업자로
PUT http://localhost:80/api/account/company/personal
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

{
  "companyNumber": "00000-1111",
  "bossName": "보스보스",
  "address": {
    "zipcode": "20202",
    "detail": "teerqwr",
    "basic": "tttt"
  },
  "openDate": "2020-01-01",
  "companyBusiness": "업종",
  "email": "oen142@naver.com",
  "phoneNumber": "010-0000-0000",
  "faxNumber": "010-000"
}


### OK 회원정보를 수정 합니다. 법인사업자로
PUT http://localhost:80/api/account/company/group
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

{
  "companyNumber": "00000-1111",
  "bossName": "보스보스",
  "address": {
    "zipcode": "20202",
    "detail": "teerqwr",
    "basic": "tttt"
  },
  "openDate": "2020-01-01",
  "companyBusiness": "업종",
  "email": "oen142@naver.com",
  "phoneNumber": "010-0000-0000",
  "faxNumber": "010-000"
}

### OK 비밀번호를 찾습니다.
PUT http://localhost:80/find-password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

{
  "username": "username",
  "name": "김종완",
  "phoneNumber": "010-1111-1111"
}

### OK 비밀번호를 수정합니다.
PUT http://localhost:80/api/account/password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

{
  "prePassword": "이전 비밀번호",
  "newPassword": "password"
}

### OK 사업자에서 개인계정으로 전환합니다.
PUT http://localhost:80/api/account/personal
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU



### OK 사업자 정보를 수정 합니다. 개인 사업자로
PUT http://localhost:80/api/account/company/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmVhbWFrZXIiLCJVU0VSTkFNRSI6ImFkbWluIiwiVVNFUl9ST0xFIjoiUk9MRV9DT01QQU5ZIn0.rVZPdzT9lT94hy6nGqgJwuV_x5ItoUn4m3upjDE-GVU

{
  "companyNumber": "00312312000-1111",
  "bossName": "보스보312312스",
  "address": {
    "zipcode": "203123202",
    "detail": "tee123123rqwr",
    "basic": "ttt123t"
  },
  "openDate": "2020-01-01",
  "companyBusiness": "업123123종",
  "email": "oen142@nav3213er.com",
  "phoneNumber": "010-1230000-0000",
  "faxNumber": "010213-000"
}